"""Constituents for Nifty indexes (Phase 17/18)."""
from typing import Dict, List

CONSTITUENTS: Dict[str, List[str]] = {
    "NIFTY50": [
        "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
        "BAJAJ-AUTO.NS", "BAJAJFINSV.NS", "BAJFINANCE.NS", "BHARTIARTL.NS", "BPCL.NS",
        "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS",
        "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
        "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "INDUSINDBK.NS",
        "INFY.NS", "ITC.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS",
        "LTIM.NS", "M&M.NS", "MARUTI.NS", "NESTLEIND.NS", "NTPC.NS",
        "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SBIN.NS",
        "SUNPHARMA.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "TCS.NS",
        "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "UPL.NS", "WIPRO.NS"
    ],
    "NIFTY_BANK": [
        "AUBANK.NS", "AXISBANK.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "FEDERALBNK.NS",
        "HDFCBANK.NS", "ICICIBANK.NS", "IDFCFIRSTB.NS", "INDUSINDBK.NS", "KOTAKBANK.NS",
        "PNB.NS", "SBIN.NS"
    ],
    "NIFTY100": [
        # Nifty 50
        "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
        "BAJAJ-AUTO.NS", "BAJAJFINSV.NS", "BAJFINANCE.NS", "BHARTIARTL.NS", "BPCL.NS",
        "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS",
        "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
        "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "INDUSINDBK.NS",
        "INFY.NS", "ITC.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS",
        "LTIM.NS", "M&M.NS", "MARUTI.NS", "NESTLEIND.NS", "NTPC.NS",
        "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SBIN.NS",
        "SUNPHARMA.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "TCS.NS",
        "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "UPL.NS", "WIPRO.NS",
        # Next 50
        "ABB.NS", "ACC.NS", "ADANIENSOL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS",
        "AMBUJACEM.NS", "BEL.NS", "BANKBARODA.NS", "BERGERPAINT.NS", "BOSCHLTD.NS",
        "CANBK.NS", "CGPOWER.NS", "CHOLAFIN.NS", "COLPAL.NS", "DLF.NS",
        "DMART.NS", "GAIL.NS", "GICRE.NS", "GODREJCP.NS", "HAL.NS",
        "HAVELLS.NS", "HINDZINC.NS", "ICICIGI.NS", "ICICIPRULI.NS", "IOC.NS",
        "IRCTC.NS", "IRFC.NS", "JINDALSTEL.NS", "JIOFIN.NS", "LICI.NS",
        "MARICO.NS", "MUTHOOTFIN.NS", "NAUKRI.NS", "PFC.NS", "PIDILITIND.NS",
        "PNB.NS", "POLYCAB.NS", "RECL.NS", "SRF.NS", "SHREECEM.NS",
        "SHRIRAMFIN.NS", "SIEMENS.NS", "TATAELXSI.NS", "TATAPOWER.NS", "TRENT.NS",
        "TVSMOTOR.NS", "UNITDSPR.NS", "VBL.NS", "VEDL.NS", "ZOMATO.NS"
    ],
    "NIFTY_MIDCAP100": [
        "ASHOKLEY.NS", "ASTRAL.NS", "AUROPHARMA.NS", "BALKRISIND.NS", "BANDHANBNK.NS",
        "BATAINDIA.NS", "BDL.NS", "BHEL.NS", "BIOCON.NS", "COFORGE.NS",
        "CONCOR.NS", "COROMANDEL.NS", "CROMPTON.NS", "CUMMINSIND.NS", "DEEPAKNTR.NS",
        "DELHIVERY.NS", "DIXON.NS", "EXIDEIND.NS", "FEDERALBNK.NS", "FORTIS.NS",
        "GLENMARK.NS", "GMRINFRA.NS", "GODREJPROP.NS", "GUJGASLTD.NS", "HINDPETRO.NS",
        "HONAUT.NS", "IEX.NS", "IGL.NS", "INDHOTEL.NS", "INDIAMART.NS",
        "INDIANB.NS", "INDIGO.NS", "IPCALAB.NS", "IRB.NS", "JSL.NS",
        "JUBLFOOD.NS", "KALYANKJIL.NS", "KEI.NS", "KPITTECH.NS", "LUPIN.NS",
        "M&MFIN.NS", "MANAPPURAM.NS", "MAPMYINDIA.NS", "MAXHEALTH.NS", "MAZDOCK.NS",
        "METROPOLIS.NS", "MGL.NS", "MPHASIS.NS", "MRF.NS", "NATIONALUM.NS",
        "NAVINFLUOR.NS", "NLCINDIA.NS", "NMDC.NS", "OBEROIRLTY.NS", "OFSS.NS",
        "OIL.NS", "PAGEIND.NS", "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS",
        "PIIND.NS", "PNBHOUSING.NS", "POONAWALLA.NS", "PRESTIGE.NS", "RAMCOCEM.NS",
        "RVNL.NS", "SAIL.NS", "SANOFI.NS", "SJVN.NS", "SKFINDIA.NS",
        "SUPREMEIND.NS", "SUZLON.NS", "SYNGENE.NS", "TATACOMM.NS", "TATAELXSI.NS",
        "TATATECH.NS", "TIMKEN.NS", "TORNTPOWER.NS", "TRIDENT.NS", "TRENT.NS",
        "TVSMOTOR.NS", "UCOBANK.NS", "UNOMINDA.NS", "VOLTAS.NS", "WHIRLPOOL.NS",
        "YESBANK.NS", "ZEEL.NS", "ZYDUSLIFE.NS"
    ]
}
